services:
  bigquery-mcp:
    build: .
    image: bigquery-mcp:latest
    container_name: bigquery-mcp-server
    volumes:
      - ./config:/app/config:ro
      - ./logs:/app/logs
      - ~/.config/gcloud:/home/mcpuser/.config/gcloud:ro
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - COMPACT_FORMAT=${COMPACT_FORMAT:-true}
      # BIGQUERY_BILLING_PROJECT is set in config.yaml
      # GOOGLE_APPLICATION_CREDENTIALS uses application default credentials
    stdin_open: true
    tty: false
    # restart: unless-stopped  # Not needed for MCP server usage
