version: '3.8'

services:
  bigquery-mcp:
    build: .
    container_name: bigquery-mcp-server
    volumes:
      - ./config:/app/config:ro
      - ./logs:/app/logs
      - ${GOOGLE_APPLICATION_CREDENTIALS:-/dev/null}:/app/credentials/service-account.json:ro
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - COMPACT_FORMAT=${COMPACT_FORMAT:-false}
      - BIGQUERY_BILLING_PROJECT=${BIGQUERY_BILLING_PROJECT:-}
      - GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS:+/app/credentials/service-account.json}
    stdin_open: true
    tty: true
    restart: unless-stopped
