services:
  bigquery-mcp:
    build: .
    container_name: bigquery-mcp-server
    volumes:
      - ./config:/app/config:ro
      - ./logs:/app/logs
      - ~/.config/gcloud:/home/mcpuser/.config/gcloud:ro
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - COMPACT_FORMAT=${COMPACT_FORMAT:-true}
      - BIGQUERY_BILLING_PROJECT=${BIGQUERY_BILLING_PROJECT:-your-billing-project}
      # No GOOGLE_APPLICATION_CREDENTIALS - let it discover automatically
    stdin_open: true
    tty: false
    # restart: unless-stopped  # Disabled for MCP usage
