services:
  # BigQuery MCP Server - Single clean service supporting CLI-first architecture
  bigquery-mcp:
    build: .
    image: bigquery-mcp:latest
    container_name: bigquery-mcp
    command: ["python", "src/server.py", "--project", "cayzer-xyz:*", "--billing-project", "cayzer-xyz"]
    volumes:
      - ./logs:/app/logs
      - ~/.config/gcloud:/home/mcpuser/.config/gcloud:ro
      # Optional: Mount config file for complex setups
      - ./config:/app/config:ro
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      # Note: CLI arguments take precedence over environment variables
      - COMPACT_FORMAT=${COMPACT_FORMAT:-false}
      - BIGQUERY_BILLING_PROJECT=${BIGQUERY_BILLING_PROJECT:-}
    stdin_open: true
    tty: false
    
    # Example configurations for different use cases:
    
    # Simple usage (single project):
    # command: ["python", "src/server.py", "--project", "my-project:*", "--billing-project", "my-project"]
    
    # Enterprise usage (multiple projects):
    # command: [
    #   "python", "src/server.py",
    #   "--project", "analytics-prod:user_*,session_*",
    #   "--project", "logs-prod:application_*,system_*", 
    #   "--project", "ml-dev:training_*,models_*",
    #   "--billing-project", "my-billing-project",
    #   "--log-level", "INFO",
    #   "--compact-format", "true",
    #   "--timeout", "300"
    # ]
    
    # Config file fallback (if no --project specified):
    # command: ["python", "src/server.py", "--config", "/app/config/config.yaml"]
