site_name: BigQuery MCP Server
site_description: A Model Context Protocol server for BigQuery with cross-project support
site_url: https://aicayzer.github.io/bigquery-mcp/
use_directory_urls: true

nav:
  - Home: index.md
  - Installation: installation.md
  - Client Setup: setup.md
  - AI Setup Assistant: ai-setup.md
  - Tools Reference: tools.md
  - Configuration: configuration.md

theme:
  name: material
  logo: assets/bigquery-icon.svg
  favicon: assets/bigquery-icon.svg
  palette:
    - scheme: default
      primary: white
      accent: light blue
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - content.code.copy

markdown_extensions:
  - codehilite
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true

plugins:
  - search

repo_url: https://github.com/aicayzer/bigquery-mcp
repo_name: bigquery-mcp